### ISSUE TITLE
Explore data inside a Jupyter notebook

### ISSUE THREAD

**Issue by julianconstantine** [caracotsios1/Titanic#4]
## Overview
For your second assignment, we're going to do some data visualization inside a Jupyter notebook. Jupyter (which stands for **Ju**lia, **Pyt**hon, and **R**) is an interactive coding environment that allows you to combine code, plots, and text all in a single location. Notebooks are a great way for beginners to get started and for professionals to do quick prototyping work and run experiments. Like GitHub, it will take you a little while to get started, but after a bit of practice, it will all become second nature and make your life a lot easier.

### Installation
You have to do a little bit of work to get Jupyter up and running, but once you do, it's fairly intuitive. I was thinking that I could walk you through the setup and basics when we talk on Monday morning. There are three basic steps:
1. Install Python 3: https://www.python.org/downloads/ (Note: In the installation process, there will be a little checkbox asking you if you want to "add Python to your PATH" or something like that. Make sure you do this)
2. Install Jupyter: https://jupyter.readthedocs.io/en/latest/install.html (You should be able to just open a command prompt and run `pip install jupyter`)
3. Install the R kernel for Jupyter: https://irkernel.github.io/installation/

### Starting Jupyter
1. Open the command prompt, `cd` into your Titanic folder, and type `jupyter notebook`. A tab should open up in your browser that displays the Jupyter console. 
2. To start a new notebook, click on the "New" dropdown menu in the upper right and select "R", this will open up an "R notebook." To start an old notebook, just click on the file you want to start up and it should open up the notebook. 

### Stopping Jupyter
1. Save the Jupyter notebook, then close the browser page with the notebook itself. 
2. Go to the Jupyter home page, click the checkbox next to the notebook file (it should be green), then click the orange "Shutdown" button. 
3. Close the browser page with the Jupyter home page.
4. Go to your command prompt, type CTRL+C to shut down Jupyter, then close the command prompt. 

## Requirements
* For each variable, create a markdown header with the variable name. Use two hashes `##` inside a Markdown cell to do this.
  * Inside another markdown cell (with text/no header), write up anything interesting you find about each variable.
* For each numeric variable in the training/testing data:
  * Print out the five-number summary (hint: see the `summary()` function)
  * Plot a histogram and label the axes (hint: see the `hist()` function)
* For each categorical variable in the training/testing data:
  * Calculate the number of observations in each category (hint: see the `table()` function)
* Do something creative on your own!

**Comment by caracotsios1** [comment]
Done!

**Comment by julianconstantine** [comment]
Hi Alexi,

I just finished looking through your notebook. Overall, it looks good (except for one error). But because my job is to be a professional nuisance about this kind of stuff at work, I have a few other suggestions for you. 😉 

**Note**: I added a file called `docker-compose.yml` to this repository. Don't worry about it. It's for a tool called "Docker" that I like to use. 

### Suggestions
0. Always rerun your code from end to end before committing it. 
1. The code that creates the histogram for `SibSp` does not work. (Hint: You're doing the right thing, but you made a typo)
2. Read the data dictionary on this [page](https://www.kaggle.com/c/titanic/data). This will tell you "WTF" `Parch` and `SibSp` are. Then add a one-sentence description of the distribution of those fields to your notebook. Do this inside by creating a new Markdown cell under the name of each variable inside the notebook. 
3. In general, don't include two commands that print output inside the same notebook cell because the output of the first command might be suppressed (i.e. not printed inside the notebook). In this case, putting `hist()` and `summary()` still shows the output for both, but this isn't always the case.

**Comment by julianconstantine** [comment]
Everything looks good to me. Closing out this issue.

Nice job Alexi. 👍
